/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'RoutingMsg'
 * message type.
 */

public class RoutingMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 52;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 7;

    /** Create a new RoutingMsg of size 52. */
    public RoutingMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new RoutingMsg of the given data_length. */
    public RoutingMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RoutingMsg with the given data_length
     * and base offset.
     */
    public RoutingMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RoutingMsg using the given byte array
     * as backing store.
     */
    public RoutingMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RoutingMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public RoutingMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RoutingMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public RoutingMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RoutingMsg embedded in the given message
     * at the given base offset.
     */
    public RoutingMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RoutingMsg embedded in the given message
     * at the given base offset and length.
     */
    public RoutingMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <RoutingMsg> \n";
      try {
        s += "  [nodeid=0x"+Long.toHexString(get_nodeid())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [NeighborAction.USED=";
        for (int i = 0; i < 10; i++) {
          s += "0x"+Long.toHexString(getElement_NeighborAction_USED(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [NeighborAction.NeighborNode=";
        for (int i = 0; i < 10; i++) {
          s += "0x"+Long.toHexString(getElement_NeighborAction_NeighborNode(i) & 0xffff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [NeighborAction.Action=";
        for (int i = 0; i < 10; i++) {
          s += "0x"+Long.toHexString(getElement_NeighborAction_Action(i) & 0xffff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: nodeid
    //   Field type: int
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'nodeid' is signed (false).
     */
    public static boolean isSigned_nodeid() {
        return false;
    }

    /**
     * Return whether the field 'nodeid' is an array (false).
     */
    public static boolean isArray_nodeid() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'nodeid'
     */
    public static int offset_nodeid() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'nodeid'
     */
    public static int offsetBits_nodeid() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'nodeid'
     */
    public int get_nodeid() {
        return (int)getUIntBEElement(offsetBits_nodeid(), 16);
    }

    /**
     * Set the value of the field 'nodeid'
     */
    public void set_nodeid(int value) {
        setUIntBEElement(offsetBits_nodeid(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'nodeid'
     */
    public static int size_nodeid() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'nodeid'
     */
    public static int sizeBits_nodeid() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: NeighborAction.USED
    //   Field type: short[]
    //   Offset (bits): 0
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'NeighborAction.USED' is signed (false).
     */
    public static boolean isSigned_NeighborAction_USED() {
        return false;
    }

    /**
     * Return whether the field 'NeighborAction.USED' is an array (true).
     */
    public static boolean isArray_NeighborAction_USED() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'NeighborAction.USED'
     */
    public static int offset_NeighborAction_USED(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 10) throw new ArrayIndexOutOfBoundsException();
        offset += 16 + index1 * 40;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'NeighborAction.USED'
     */
    public static int offsetBits_NeighborAction_USED(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 10) throw new ArrayIndexOutOfBoundsException();
        offset += 16 + index1 * 40;
        return offset;
    }

    /**
     * Return the entire array 'NeighborAction.USED' as a short[]
     */
    public short[] get_NeighborAction_USED() {
        short[] tmp = new short[10];
        for (int index0 = 0; index0 < numElements_NeighborAction_USED(0); index0++) {
            tmp[index0] = getElement_NeighborAction_USED(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'NeighborAction.USED' from the given short[]
     */
    public void set_NeighborAction_USED(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_NeighborAction_USED(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'NeighborAction.USED'
     */
    public short getElement_NeighborAction_USED(int index1) {
        return (short)getUIntBEElement(offsetBits_NeighborAction_USED(index1), 8);
    }

    /**
     * Set an element of the array 'NeighborAction.USED'
     */
    public void setElement_NeighborAction_USED(int index1, short value) {
        setUIntBEElement(offsetBits_NeighborAction_USED(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'NeighborAction.USED'
     */
    public static int totalSize_NeighborAction_USED() {
        return (400 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'NeighborAction.USED'
     */
    public static int totalSizeBits_NeighborAction_USED() {
        return 400;
    }

    /**
     * Return the size, in bytes, of each element of the array 'NeighborAction.USED'
     */
    public static int elementSize_NeighborAction_USED() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'NeighborAction.USED'
     */
    public static int elementSizeBits_NeighborAction_USED() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'NeighborAction.USED'
     */
    public static int numDimensions_NeighborAction_USED() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'NeighborAction.USED'
     */
    public static int numElements_NeighborAction_USED() {
        return 10;
    }

    /**
     * Return the number of elements in the array 'NeighborAction.USED'
     * for the given dimension.
     */
    public static int numElements_NeighborAction_USED(int dimension) {
      int array_dims[] = { 10,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'NeighborAction.USED' with a String
     */
    public void setString_NeighborAction_USED(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_NeighborAction_USED(i, (short)s.charAt(i));
         }
         setElement_NeighborAction_USED(i, (short)0); //null terminate
    }

    /**
     * Read the array 'NeighborAction.USED' as a String
     */
    public String getString_NeighborAction_USED() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,10)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_NeighborAction_USED(i) == (char)0) break;
             carr[i] = (char)getElement_NeighborAction_USED(i);
         }
         return new String(carr,0,i);
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: NeighborAction.NeighborNode
    //   Field type: int[]
    //   Offset (bits): 8
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'NeighborAction.NeighborNode' is signed (false).
     */
    public static boolean isSigned_NeighborAction_NeighborNode() {
        return false;
    }

    /**
     * Return whether the field 'NeighborAction.NeighborNode' is an array (true).
     */
    public static boolean isArray_NeighborAction_NeighborNode() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'NeighborAction.NeighborNode'
     */
    public static int offset_NeighborAction_NeighborNode(int index1) {
        int offset = 8;
        if (index1 < 0 || index1 >= 10) throw new ArrayIndexOutOfBoundsException();
        offset += 16 + index1 * 40;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'NeighborAction.NeighborNode'
     */
    public static int offsetBits_NeighborAction_NeighborNode(int index1) {
        int offset = 8;
        if (index1 < 0 || index1 >= 10) throw new ArrayIndexOutOfBoundsException();
        offset += 16 + index1 * 40;
        return offset;
    }

    /**
     * Return the entire array 'NeighborAction.NeighborNode' as a int[]
     */
    public int[] get_NeighborAction_NeighborNode() {
        int[] tmp = new int[10];
        for (int index0 = 0; index0 < numElements_NeighborAction_NeighborNode(0); index0++) {
            tmp[index0] = getElement_NeighborAction_NeighborNode(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'NeighborAction.NeighborNode' from the given int[]
     */
    public void set_NeighborAction_NeighborNode(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_NeighborAction_NeighborNode(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'NeighborAction.NeighborNode'
     */
    public int getElement_NeighborAction_NeighborNode(int index1) {
        return (int)getUIntBEElement(offsetBits_NeighborAction_NeighborNode(index1), 16);
    }

    /**
     * Set an element of the array 'NeighborAction.NeighborNode'
     */
    public void setElement_NeighborAction_NeighborNode(int index1, int value) {
        setUIntBEElement(offsetBits_NeighborAction_NeighborNode(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'NeighborAction.NeighborNode'
     */
    public static int totalSize_NeighborAction_NeighborNode() {
        return (400 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'NeighborAction.NeighborNode'
     */
    public static int totalSizeBits_NeighborAction_NeighborNode() {
        return 400;
    }

    /**
     * Return the size, in bytes, of each element of the array 'NeighborAction.NeighborNode'
     */
    public static int elementSize_NeighborAction_NeighborNode() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'NeighborAction.NeighborNode'
     */
    public static int elementSizeBits_NeighborAction_NeighborNode() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'NeighborAction.NeighborNode'
     */
    public static int numDimensions_NeighborAction_NeighborNode() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'NeighborAction.NeighborNode'
     */
    public static int numElements_NeighborAction_NeighborNode() {
        return 10;
    }

    /**
     * Return the number of elements in the array 'NeighborAction.NeighborNode'
     * for the given dimension.
     */
    public static int numElements_NeighborAction_NeighborNode(int dimension) {
      int array_dims[] = { 10,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: NeighborAction.Action
    //   Field type: int[]
    //   Offset (bits): 24
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'NeighborAction.Action' is signed (false).
     */
    public static boolean isSigned_NeighborAction_Action() {
        return false;
    }

    /**
     * Return whether the field 'NeighborAction.Action' is an array (true).
     */
    public static boolean isArray_NeighborAction_Action() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'NeighborAction.Action'
     */
    public static int offset_NeighborAction_Action(int index1) {
        int offset = 24;
        if (index1 < 0 || index1 >= 10) throw new ArrayIndexOutOfBoundsException();
        offset += 16 + index1 * 40;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'NeighborAction.Action'
     */
    public static int offsetBits_NeighborAction_Action(int index1) {
        int offset = 24;
        if (index1 < 0 || index1 >= 10) throw new ArrayIndexOutOfBoundsException();
        offset += 16 + index1 * 40;
        return offset;
    }

    /**
     * Return the entire array 'NeighborAction.Action' as a int[]
     */
    public int[] get_NeighborAction_Action() {
        int[] tmp = new int[10];
        for (int index0 = 0; index0 < numElements_NeighborAction_Action(0); index0++) {
            tmp[index0] = getElement_NeighborAction_Action(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'NeighborAction.Action' from the given int[]
     */
    public void set_NeighborAction_Action(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_NeighborAction_Action(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'NeighborAction.Action'
     */
    public int getElement_NeighborAction_Action(int index1) {
        return (int)getUIntBEElement(offsetBits_NeighborAction_Action(index1), 16);
    }

    /**
     * Set an element of the array 'NeighborAction.Action'
     */
    public void setElement_NeighborAction_Action(int index1, int value) {
        setUIntBEElement(offsetBits_NeighborAction_Action(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'NeighborAction.Action'
     */
    public static int totalSize_NeighborAction_Action() {
        return (400 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'NeighborAction.Action'
     */
    public static int totalSizeBits_NeighborAction_Action() {
        return 400;
    }

    /**
     * Return the size, in bytes, of each element of the array 'NeighborAction.Action'
     */
    public static int elementSize_NeighborAction_Action() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'NeighborAction.Action'
     */
    public static int elementSizeBits_NeighborAction_Action() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'NeighborAction.Action'
     */
    public static int numDimensions_NeighborAction_Action() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'NeighborAction.Action'
     */
    public static int numElements_NeighborAction_Action() {
        return 10;
    }

    /**
     * Return the number of elements in the array 'NeighborAction.Action'
     * for the given dimension.
     */
    public static int numElements_NeighborAction_Action(int dimension) {
      int array_dims[] = { 10,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

}
